✏️ fixed casing and minor typos
DarqueWarrior/vsteam pull request #418
Opened 2021-09-17 19:06 UTC by smholvoet

# PR Summary

Fixed casing and a couple of minor typos.

## Suggestion

Another suggestion (which I have not yet pushed to my branch) is reworking the **Notes** section. I personally think it's very annoying seeing relevant cmdlets mentioned there, which are not clickable. Granted, they are mentioned a bit further down in the **Related links** section, but I think making the cmdlets clickable in the **Notes** section prevents a user from having to scroll further down and find the exact cmdlet he was looking for in a list of (sometimes) _many_ more cmdlets.

I've noticed some cmdlets have related links which get added below the cmdlets which are displayed through the [prerequisites.md ](https://github.com/MethodsAndPractices/vsteam/blob/trunk/.docs/common/prerequisites.md)file, for example [Update-VSTeamPolicy](https://github.com/MethodsAndPractices/vsteam/blob/a5d2ebebe8277861904c71229c31ddd6a02f7fe9/.docs/Update-VSTeamPolicy.md), which I think is very useful.

In summary:

- Remove `` from the Related links section
- Rework the Notes section to include link, making things easier for users

Let me know what you think and I'll push additional changes to this branch should you agree with the above suggestion.

## PR Checklist

- [ ] [Write Help](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-help)
- [ ] [Write Unit Test](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-unit-test)
- [ ] [Update CHANGELOG.md](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#update-changelogmd)

2021-09-18 12:45 UTC, SebastianSchuetze commented
Are you talking about the github docs pages regarding the links of the source markdown pages?

2021-09-19 16:00 UTC, smholvoet commented
@SebastianSchuetze I'm indeed talking about the docs page, for example: [Get-VSTeamAccounts](https://methodsandpractices.github.io/vsteam-docs/docs/modules/vsteam/commands/Get-VSTeamAccounts#notes).

So in short: 

1. Remove the fixed commands which get added to the _Related links_ section, which has been added to every command:
![image](https://user-images.githubusercontent.com/13507392/133934207-080eea85-c6fa-4504-aade-031effbd531c.png)

2. Rework the [_Notes_ section](https://github.com/MethodsAndPractices/vsteam/blob/trunk/.docs/common/prerequisites.md) to include direct links to any cmdlet that gets mentioned there.

2021-10-03 20:18 UTC, SebastianSchuetze commented
@DarqueWarrior what was the intention to add the standard related texts in every cmdlet? Is this nessecary to mention it everywhere?

2021-10-04 04:54 UTC, SebastianSchuetze commented
@smholvoet  you can remove the related part. You are right, that it may be deserve it's own page once instead of having it on every cmdlet.

> @SebastianSchuetze I'm indeed talking about the docs page, for example: [Get-VSTeamAccounts](https://methodsandpractices.github.io/vsteam-docs/docs/modules/vsteam/commands/Get-VSTeamAccounts#notes).
> 
> So in short:
> 
> 1. Remove the fixed commands which get added to the _Related links_ section, which has been added to every command:
>    ![image](https://user-images.githubusercontent.com/13507392/133934207-080eea85-c6fa-4504-aade-031effbd531c.png)
> 2. Rework the [_Notes_ section](https://github.com/MethodsAndPractices/vsteam/blob/trunk/.docs/common/prerequisites.md) to include direct links to any cmdlet that gets mentioned there.

2021-10-04 06:26 UTC, SebastianSchuetze requested changes
Checked your current code.

Since unit tests are failing, then I guess you are not finished yet.

2021-10-04 06:26 UTC, SebastianSchuetze commented on .docs/Get-VSTeamWorkItemTag.md
> +You must call `Set-VSTeamAccount` before calling this function.
This you don't need to add since this is valid for all cmdlet. There is even an error if you try to do this.

```suggestion
```

2021-10-04 06:26 UTC, SebastianSchuetze commented on .docs/Remove-VSTeamWorkItemTag.md
> +You must call `Set-VSTeamAccount` before calling this function.
```suggestion
```

2021-10-04 06:26 UTC, SebastianSchuetze commented on .docs/Update-VSTeamWorkItemTag.md
> +You must call `Set-VSTeamAccount` before calling this function.
```suggestion
```

2021-10-04 06:26 UTC, SebastianSchuetze commented on Source/Public/Get-VSTeamWorkItemTag.ps1
> +      [string] $TagIdOrName,
Question. API says that in the object ID and name are two different properties. But in the URL it does not care if you use the name or the GUID?

2021-10-04 06:26 UTC, SebastianSchuetze commented on Source/Public/Remove-VSTeamWorkItemTag.ps1
> +      if ($Force -or $pscmdlet.ShouldProcess($item, "Delete Work Item Tag")) {
The message could be a bit clearer. Something like:

"Delete work Item tag from all work items in the project"

2021-10-04 06:26 UTC, SebastianSchuetze commented on Source/Public/Update-VSTeamWorkItemTag.ps1
> +      if ($Force -or $pscmdlet.ShouldProcess($Id, "Update Work Item Tag")) {
Same message a bit clearer like with remove.

2021-10-04 06:26 UTC, SebastianSchuetze commented on Tests/function/tests/Remove-VSTeamWorkItemTag.Tests.ps1
> +         #TODO
What is missing here?

2021-10-10 18:39 UTC, SebastianSchuetze commented
@smholvoet any update on your PR?

2021-10-10 18:51 UTC, smholvoet commented
@SebastianSchuetze I'll rework this in the next couple of days, thank you for reviewing 👌

Can I go ahead and rework the "related links" section as well? This would impact 172 files (all cmdlets).
Or should I hold off on this until @DarqueWarrior's response clears [this](https://github.com/MethodsAndPractices/vsteam/pull/418#issuecomment-933018716) up? 🤔

> @DarqueWarrior what was the intention to add the standard related texts in every cmdlet? Is this nessecary to mention it everywhere?

2021-10-11 04:49 UTC, SebastianSchuetze commented
No it's fine. You can rework. Please just do it in an extra PR.

Thanks for the support. Appreciate it!

2021-10-22 18:48 UTC, SebastianSchuetze commented
@smholvoet got any time to finish it? :-)

2021-10-23 07:52 UTC, smholvoet commented on .docs/Get-VSTeamWorkItemTag.md
> +You must call `Set-VSTeamAccount` before calling this function.
Removed this line.

2021-10-23 07:52 UTC, smholvoet commented on .docs/Remove-VSTeamWorkItemTag.md
> +You must call `Set-VSTeamAccount` before calling this function.
Removed this line.

2021-10-23 07:52 UTC, smholvoet commented on .docs/Update-VSTeamWorkItemTag.md
> +You must call `Set-VSTeamAccount` before calling this function.
Removed this line.

2021-10-23 07:54 UTC, smholvoet commented on Source/Public/Get-VSTeamWorkItemTag.ps1
> +      [string] $TagIdOrName,
Both the Object ID and name should work here, they even called the parameter `tagIdOrName` 🤷‍♂️.

See [Tags - Get](https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/tags/get?view=azure-devops-rest-6.0).

2021-10-23 07:55 UTC, smholvoet commented on Source/Public/Remove-VSTeamWorkItemTag.ps1
> +      if ($Force -or $pscmdlet.ShouldProcess($item, "Delete Work Item Tag")) {
Updated the description.

2021-10-23 07:56 UTC, smholvoet commented on Source/Public/Update-VSTeamWorkItemTag.ps1
> +      if ($Force -or $pscmdlet.ShouldProcess($Id, "Update Work Item Tag")) {
Updated the description.

2021-10-23 07:58 UTC, smholvoet commented on Tests/function/tests/Remove-VSTeamWorkItemTag.Tests.ps1
> +         #TODO
Both `Invoke-Restmethod` calls were using an incorrect variable, updated this one.

2021-10-23 08:42 UTC, SebastianSchuetze commented
@smholvoet thanks for you work! Please also check the builds. Your unit tests do not seem to go through. Without this we cannot merge.

![image](https://user-images.githubusercontent.com/7256168/138549568-855b0789-9719-4b11-9c65-91c7202f2a1d.png)

2021-10-23 10:55 UTC, SebastianSchuetze requested changes
Just saw the file docs/synopsis/Update-VSTeamWorkItemTag.md

Synopsis is missing there.

You can also run the unit tests locally to check if they work.

https://github.com/MethodsAndPractices/vsteam/blob/trunk/README.md#how-to-build-locally

2022-01-11 22:47 UTC, SebastianSchuetze approved these changes, later dismissed
Made quite some changes to the unit test. I guess you didn't run them at all locally. :-)

But really thank you for introducing this. I need to check a view more things, then I can merge this.

2022-01-11 23:12 UTC, SebastianSchuetze approved these changes

2022-01-11 23:15 UTC, merged